package model;
// Generated 10/12/2012 11:24:23 by Hibernate Tools 3.2.1.GA



/**
 * Hashaux generated by hbm2java
 */
public class Hashaux  implements java.io.Serializable {

     private long idha;
     private long idh;
     private long idt;

    public Hashaux() {
    }

    public Hashaux(long idha, long idh, long idt) {
       this.idh = idha;
       this.idh = idh;
       this.idt = idt;
    }
   
    public long getIdh() {
        return this.idh;
    }
    
    public void setIdh(long idh) {
        this.idh = idh;
    }
    public long getIdt() {
        return this.idt;
    }
    
    public void setIdt(long idt) {
        this.idt = idt;
    }

    public long getIdha() {
        return idha;
    }

    public void setIdha(long idha) {
        this.idha = idha;
    }




}


