package model;
// Generated 05/12/2012 13:20:03 by Hibernate Tools 3.2.1.GA



/**
 * Hashaux generated by hbm2java
 */
public class Hashaux  implements java.io.Serializable {


     private long idh;
     private long idt;

    public Hashaux() {
    }

    public Hashaux(long idh, long idt) {
       this.idh = idh;
       this.idt = idt;
    }
   
    public long getIdh() {
        return this.idh;
    }
    
    public void setIdh(long idh) {
        this.idh = idh;
    }
    public long getIdt() {
        return this.idt;
    }
    
    public void setIdt(long idt) {
        this.idt = idt;
    }




}


