package model;
// Generated 05/12/2012 13:20:03 by Hibernate Tools 3.2.1.GA



/**
 * Relaciones generated by hbm2java
 */
public class Relaciones  implements java.io.Serializable {


     private long idusuario;
     private long seguidor;

    public Relaciones() {
    }

    public Relaciones(long idusuario, long seguidor) {
       this.idusuario = idusuario;
       this.seguidor = seguidor;
    }
   
    public long getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(long idusuario) {
        this.idusuario = idusuario;
    }
    public long getSeguidor() {
        return this.seguidor;
    }
    
    public void setSeguidor(long seguidor) {
        this.seguidor = seguidor;
    }




}


