package model;
// Generated 10/12/2012 11:24:23 by Hibernate Tools 3.2.1.GA



/**
 * Relaciones generated by hbm2java
 */
public class Relaciones  implements java.io.Serializable {


     private Integer idr;
     private int idusuario;
     private String siguiendo;

    public Relaciones() {
    }

    public Relaciones(int idusuario, String siguiendo) {
       this.idusuario = idusuario;
       this.siguiendo = siguiendo;
    }
   
    public Integer getIdr() {
        return this.idr;
    }
    
    public void setIdr(Integer idr) {
        this.idr = idr;
    }
    public int getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(int idusuario) {
        this.idusuario = idusuario;
    }
    public String getSiguiendo() {
        return this.siguiendo;
    }
    
    public void setSiguiendo(String siguiendo) {
        this.siguiendo = siguiendo;
    }




}


