package model;
// Generated 05/12/2012 13:20:03 by Hibernate Tools 3.2.1.GA

import com.opensymphony.xwork2.ActionContext;
import java.sql.Timestamp;
import java.util.Map;




/**
 * Twits generated by hbm2java
 */
public class Twits  implements java.io.Serializable {

 java.util.Date date= new java.util.Date();

     private Long idt;
     private Long idu;
     private String string;
     private String timestam;

    public Twits() {
    }

    public Twits(long idu, String string, String timestam) {
       this.idu = idu;
       this.string = string;
       this.timestam = timestam;
    }
   
    public Long getIdt() {
        return this.idt;
    }
    
    public void setIdt(Long idt) {
        this.idt = idt;
    }
    public long getIdu() {
        return this.idu;
    }
    
    public void setIdu(Long idu) {
       Map auth = ActionContext.getContext().getSession();
         Integer i = auth.get("idusuario").hashCode();
         this.idu = i.longValue();
    }
    public String getString() {
        return this.string;
    }
    
    public void setString(String string) {
        this.string = string;
    }
    public String getTimestam() {
        return this.timestam;
    }
    
    public void setTimestam(String timestam) {
        this.timestam = new Timestamp(date.getTime()).toString();
    }




}


