package modelo.entidades;
// Generated Oct 1, 2012 2:55:42 PM by Hibernate Tools 3.2.1.GA



/**
 * Hashtags generated by hbm2java
 */
public class Hashtags  implements java.io.Serializable {


     private Long idh;
     private String string;
     private String firstcreator;
     private long idu;

    public Hashtags() {
    }

    public Hashtags(String string, String firstcreator, long idu) {
       this.string = string;
       this.firstcreator = firstcreator;
       this.idu = idu;
    }
   
    public Long getIdh() {
        return this.idh;
    }
    
    public void setIdh(Long idh) {
        this.idh = idh;
    }
    public String getString() {
        return this.string;
    }
    
    public void setString(String string) {
        this.string = string;
    }
    public String getFirstcreator() {
        return this.firstcreator;
    }
    
    public void setFirstcreator(String firstcreator) {
        this.firstcreator = firstcreator;
    }
    public long getIdu() {
        return this.idu;
    }
    
    public void setIdu(long idu) {
        this.idu = idu;
    }




}


