package modelo.entidades;
// Generated Oct 1, 2012 2:55:42 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private Long idu;
     private String nombre;
     private String bio;
     private Date date;
     private String mail;
     private String pass;
     private String imagen;

    public Usuarios() {
    }

    public Usuarios(String nombre, String bio, Date date, String mail, String pass, String imagen) {
       this.nombre = nombre;
       this.bio = bio;
       this.date = date;
       this.mail = mail;
       this.pass = pass;
       this.imagen = imagen;
    }
   
    public Long getIdu() {
        return this.idu;
    }
    
    public void setIdu(Long idu) {
        this.idu = idu;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getBio() {
        return this.bio;
    }
    
    public void setBio(String bio) {
        this.bio = bio;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }
    public String getImagen() {
        return this.imagen;
    }
    
    public void setImagen(String imagen) {
        this.imagen = imagen;
    }




}


